PROGNAME=thee
VERSION=1.0

MKDIR=mkdir
PACK=tar -jcvf
CC=gcc
CFLAGS=-Wall -Wextra -Werror -pedantic -std=c99 -lm
CP=cp
RM=rm -rf
OFILES=$(subst .c,.o,$(wildcard *.c))

run: all

all: thee1 thee2 thee3

thee1: loods1.o thee1.c
    $(CC) $(CFLAGS) -o thee1 loods1.o thee1.c

thee2: loods1.o thee2.c
    $(CC) $(CFLAGS) -o thee2 loods1.o thee2.c

thee3: loods3.o thee1.c
    $(CC) $(CFLAGS) -o thee3 loods3.o thee1.c
    
clean:
	$(RM) *.o thee1 thee2 thee3 10183159_$(PROGNAME).tbz



tarball: $(PROGNAME)
	$(MAKE) clean
	$(MKDIR) 10183159_$(PROGNAME)
	$(CP) * 10183159_$(PROGNAME) || true
	$(PACK) 10183159_$(PROGNAME).tbz 10183159_$(PROGNAME)/*
	$(RM) 10183159_$(PROGNAME)
